# Generated by Django 3.2.3 on 2021-10-04 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import handsons.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handsons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='handsonmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='handsoncontent',
            name='handson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handsons.handson'),
        ),
        migrations.AddField(
            model_name='handson',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET(handsons.models.get_deleted_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentpassmember',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handsons.handsoncontent'),
        ),
        migrations.AddField(
            model_name='contentpassmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
