# Generated by Django 3.1.5 on 2021-01-06 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import handsons.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Handson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('headline', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('require', models.TextField()),
                ('document_url', models.URLField()),
                ('meeting_url', models.URLField()),
                ('movie_url', models.URLField()),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_public', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('f', 'future'), ('o', 'open'), ('c', 'closed'), ('p', 'past')], max_length=50)),
                ('owner', models.ForeignKey(on_delete=models.SET(handsons.models.get_deleted_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Handson',
                'verbose_name_plural': 'Handsons',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HandsonMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handsons.handson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HandsonMember',
                'verbose_name_plural': 'HandsonMembers',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HandsonContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('handson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handsons.handson')),
            ],
            options={
                'verbose_name': 'HandsonContent',
                'verbose_name_plural': 'HandsonContents',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContentPassMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handsons.handsoncontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ContentPassMember',
                'verbose_name_plural': 'ContentPassMembers',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
