# Generated by Django 3.1.5 on 2021-05-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handsons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handson',
            name='status',
        ),
    ]
